#!/usr/bin/env node
/**
 * Copies the ts-fsrs ES module build into vendor/ so the app can load it.
 *
 * There is no bundler here on purpose: index.html loads plain ES modules and
 * build.cjs concatenates them. A bare specifier like `import ... from 'ts-fsrs'`
 * means nothing to a browser, and pointing at node_modules over HTTP would make
 * the app depend on an install layout. Vendoring the dist file keeps the module
 * app runnable from any static server and lets build.cjs inline the library into
 * the offline bundle the same way it inlines everything else.
 *
 * Re-run after changing the ts-fsrs version in package.json. The version in
 * package.json is the source of truth; vendor/ts-fsrs.js is a build artifact
 * that happens to be committed.
 */

const fs = require('fs');
const path = require('path');

const ROOT = __dirname;
const SRC = path.join(ROOT, 'node_modules', 'ts-fsrs', 'dist', 'index.mjs');
const OUT = path.join(ROOT, 'vendor', 'ts-fsrs.js');

if (!fs.existsSync(SRC)) {
  console.error('ts-fsrs is not installed. Run `npm install` first.');
  process.exit(1);
}

const version = require(path.join(ROOT, 'node_modules', 'ts-fsrs', 'package.json')).version;

const body = fs.readFileSync(SRC, 'utf8')
  // the .map is not shipped, so a dangling sourceMappingURL is just a 404
  .replace(/\n\/\/# sourceMappingURL=.*\s*$/, '\n');

const header =
  `/* ts-fsrs ${version} — vendored from node_modules/ts-fsrs/dist/index.mjs.\n` +
  ` * Generated by vendor.cjs. Do not edit; run \`npm run vendor\` instead. */\n`;

fs.mkdirSync(path.dirname(OUT), { recursive: true });
fs.writeFileSync(OUT, header + body);
console.log(`vendor/ts-fsrs.js  ts-fsrs ${version}, ${Buffer.byteLength(header + body)} bytes`);
